datasets:
  S3DIS:
    name: &dataset_name 'S3DIS'
    type: 'S3DIS'
    root: &root_dir !join ['datasets/', *dataset_name]
    splits:
      train:
        dataset_id: *root_dir
        params:
          root: *root_dir
          test_area: 5
          train: True
          pre_transform:
            - &normalize
              type: 'NormalizeScale'
      val:
        dataset_id: *root_dir
        params:
          root: *root_dir
          test_area: 5
          train: False
          pre_transform:
            - *normalize

models:
  student_model:
    name: &student_model_name 'dense_deep_gcn'
    params:
      opt: 
    experiment: &student_experiment !join [*dataset_name, '-', *student_model_name]
    ckpt: !join ['custom_models/sem_seg_dense-res-edge-28-64_02.pth']

train:
  log_freq: 1
  num_epochs: 20
  train_data_loader:
    dataset_id: *root_dir
    random_sample: True
    batch_size: 1
    num_workers: 12
    cache_output:
    dataset_wrapper:
        name: 'GeometricWrapper'
        params: {}
    #collate_fn: collate_fn
  val_data_loader:
    dataset_id: *root_dir
    random_sample: False
    batch_size: 1
    num_workers: 12
    dataset_wrapper:
        name: 'GeometricWrapper'
        params: {}
    #collate_fn: collate_fn
  teacher:
    sequential: []
    wrapper: 'DistributedDataParallel'
    requires_grad: False
  student:
    adaptations:
    sequential: []
    wrapper: 'DistributedDataParallel'
    requires_grad: True
    frozen_modules: []
  apex:
    requires: False
    opt_level: '01'
  optimizer:
    type: 'Adam'
    params:
      lr: 0.0001
      #momentum: 0.9
      #weight_decay: 0.0005
  scheduler:
    type: 'MultiStepLR'
    params:
      milestones: [5, 15]
      gamma: 0.1
  criterion:
    type: 'GeneralizedCustomLoss'
    org_term:
      criterion:
        type: 'CrossEntropyLoss'
        params:
      factor: 1.0
    sub_terms:

test:
  log_freq: 100
  test_data_loader:
    dataset_id: *root_dir
    random_sample: False
    batch_size: 1
    num_workers: 12
    dataset_wrapper:
        name: 'GeometricWrapper'
        params: {}
    #collate_fn: collate_fn